#!/usr/bin/env python3
"""Write the compose override that lets the Dolt server see every repository the loads wrote.

  python3 scripts/dolt_server_config.py

`dolt sql-server` serves the directories one level under its data directory that hold a `.dolt`.
The timed runner keeps each database in its own data directory -- `data/dolt/<db>/<db>` -- so
that a command over one database does not open all of them, and the older loader wrote
`data/dolt/<db>`. The server's yaml config (Dolt 2.3) has no list of databases to point it at
paths, so the mapping is done with bind mounts instead: `compose.override.yaml`, which compose
merges into `compose.yaml` on its own, mounts every repository at `/var/lib/dolt/<db>`. `make up`
writes it first; it is generated from the data directory and not committed.
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT  # noqa: E402

DATA = os.path.join(ROOT, "data", "dolt")
OUT = os.path.join(ROOT, "compose.override.yaml")


def repositories():
    """{name: path on the host}: the runner's nested layout first, then the flat one."""
    found = {}
    if not os.path.isdir(DATA):
        return found
    for name in sorted(os.listdir(DATA)):
        nested = os.path.join(DATA, name, name, ".dolt")
        flat = os.path.join(DATA, name, ".dolt")
        if os.path.isdir(nested):
            found[name] = f"./data/dolt/{name}/{name}"
        elif os.path.isdir(flat):
            found[name] = f"./data/dolt/{name}"
    return found


def main():
    repos = repositories()
    lines = ["# Generated by scripts/dolt_server_config.py from data/dolt/ -- do not edit; `make up` rewrites it.",
             "# Each repository the loads wrote, mounted where `dolt sql-server` looks for a database.",
             "services:", "  dolt:", "    volumes:"]
    for name, path in repos.items():
        lines.append(f"      - {path}:/var/lib/dolt/{name}")
    if not repos:
        lines.append("      []")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"  . wrote {os.path.relpath(OUT, ROOT)}: {len(repos)} databases mounted for the Dolt server")
    return 0


if __name__ == "__main__":
    sys.exit(main())
