#!/usr/bin/env python3
"""Turn the measurements into the report, and splice the results into README.md.

  python3 scripts/report.py [--check]

Writes `REPORT.md` -- every database, both engines, the ratio -- and replaces the block between
`<!-- results:start -->` and `<!-- results:end -->` in `README.md` with the summary table. Both are
generated from `build/results.json`, so the numbers in the README are the numbers that were measured
and cannot be edited into something more flattering. `--check` exits non-zero if either is stale.
"""
import argparse, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, human, load_results  # noqa: E402

RAW = {}
REPORT = os.path.join(ROOT, "REPORT.md")
README = os.path.join(ROOT, "README.md")
START, END = "<!-- results:start -->", "<!-- results:end -->"
ENV_START, ENV_END = "<!-- environment:start -->", "<!-- environment:end -->"
GENERATED = ("<!-- Generated by scripts/report.py from build/results.json.\n"
             "     Do not edit by hand: `make report` overwrites it. -->")


def rows(results):
    out = []
    for db in sorted(results):
        r = results[db]
        modes = r.get("modes", {})
        one = modes.get("oneshot", {}) or {}
        my, do = r.get("mysql_disk_bytes"), one.get("disk_bytes")
        if not my or not do:
            continue
        one_t = one.get("total_seconds")
        out.append(dict(db=db, mysql=my, dolt=do, ratio=do / my,
                        mysql_seconds=r.get("mysql_load_seconds"),
                        mysql_rowwise_seconds=r.get("mysql_rowwise_seconds"),
                        mysql_rowwise_bytes=r.get("mysql_rowwise_bytes"),
                        dolt_seconds=one_t,
                        rowinsert_seconds=(modes.get("rowinsert", {}) or {}).get("total_seconds"),
                        rowcommit_seconds=(modes.get("rowcommit", {}) or {}).get("total_seconds"),
                        rowinsert=(modes.get("rowinsert", {}) or {}).get("disk_bytes"),
                        rowcommit=(modes.get("rowcommit", {}) or {}).get("disk_bytes"),
                        rowcommit_commits=(modes.get("rowcommit", {}) or {}).get("commits"),
                        stats=one.get("stats_bytes") or 0,
                        idx_my=r.get("indexes_mysql") or 0, idx_do=one.get("indexes_dolt") or 0,
                        idx_diff=bool(one.get("indexes_only_mysql") or one.get("indexes_only_dolt")),
                        commits=one.get("commits"),
                        views_my=r.get("views_mysql") or 0, views_do=one.get("views_dolt") or 0,
                        rout_my=r.get("routines_mysql") or 0, rout_do=one.get("routines_dolt") or 0,
                        logical=r.get("mysql_logical_bytes") or 0,
                        dump=r.get("dump_bytes") or 0,
                        tables=r.get("tables") or 0, rows=r.get("rows_mysql") or 0,
                        mismatch=bool(one.get("row_mismatches")),
                        errors=one.get("statement_error_count", 0),
                        # the same three row-by-row loads with every index maintained throughout
                        mysql_rowwise_bytes_inline=r.get("mysql_rowwise_bytes_inline"),
                        mysql_rowwise_seconds_inline=r.get("mysql_rowwise_seconds_inline"),
                        rowinsert_inline=(modes.get("rowinsert_inline", {}) or {}).get("disk_bytes"),
                        rowinsert_seconds_inline=(modes.get("rowinsert_inline", {})
                                                  or {}).get("total_seconds"),
                        rowcommit_inline=(modes.get("rowcommit_inline", {}) or {}).get("disk_bytes"),
                        rowcommit_seconds_inline=(modes.get("rowcommit_inline", {})
                                                  or {}).get("total_seconds"),
                        # index parity per mode, not only for the one-shot load: the row-by-row
                        # loads under both index policies have to end with the same indexes too,
                        # and the deferred policy is precisely the one that rebuilds them by hand
                        idx_by_mode={m: {"dolt": v.get("indexes_dolt"),
                                         "only_mysql": v.get("indexes_only_mysql") or [],
                                         "only_dolt": v.get("indexes_only_dolt") or []}
                                     for m, v in modes.items()
                                     if isinstance(v, dict) and v.get("indexes_dolt") is not None}))
    return out


MODE_TITLES = {"oneshot": "one commit per database",
               "rowinsert": "one `INSERT` per row, indexes deferred",
               "rowcommit": "one commit per row, indexes deferred",
               "rowinsert_inline": "one `INSERT` per row, indexes maintained",
               "rowcommit_inline": "one commit per row, indexes maintained"}


def index_parity_table(items):
    """Index parity for every mode that was measured, not just the one-shot load."""
    modes = sorted({m for i in items for m in i["idx_by_mode"]},
                   key=lambda m: list(MODE_TITLES).index(m) if m in MODE_TITLES else 99)
    if not modes:
        return []
    L = ["| Dolt load | databases checked | indexes in MySQL | indexes in Dolt | disagreements |",
         "|---|---:|---:|---:|---|"]
    for m in modes:
        have = [i for i in items if m in i["idx_by_mode"]]
        my = sum(i["idx_my"] for i in have)
        do = sum(i["idx_by_mode"][m]["dolt"] or 0 for i in have)
        bad = [i["db"] for i in have
               if i["idx_by_mode"][m]["only_mysql"] or i["idx_by_mode"][m]["only_dolt"]]
        L.append(f"| {MODE_TITLES.get(m, m)} | {len(have)} | {my} | {do} | "
                 + (", ".join(f"`{d}`" for d in bad) if bad else "none") + " |")
    return L


POLICY_PAIRS = [("mysql_rowwise_bytes", "mysql_rowwise_bytes_inline",
                 "mysql_rowwise_seconds", "mysql_rowwise_seconds_inline",
                 "MySQL, one `INSERT` per row"),
                ("rowinsert", "rowinsert_inline",
                 "rowinsert_seconds", "rowinsert_seconds_inline",
                 "Dolt, one `INSERT` per row, one commit"),
                ("rowcommit", "rowcommit_inline",
                 "rowcommit_seconds", "rowcommit_seconds_inline",
                 "Dolt, one commit per row")]


def policy_section(items):
    """Deferred against inline, every database, both axes.

    The figure shows the shape; this is where the numbers live, which is also the relief for the
    palette's low-contrast hues -- nothing here is readable only as a colour."""
    L = ["## What maintaining the indexes costs", "",
         "Tests 2, 4 and 5 run twice: once with the secondary indexes and foreign keys dropped for "
         "the load and rebuilt afterwards, and once with every index maintained on every row. "
         "Everything else is identical, including the final schema. A positive number means "
         "keeping the indexes cost more.", ""]
    any_data = False
    for db_b, in_b, db_t, in_t, title in POLICY_PAIRS:
        have = [i for i in items if i.get(db_b) and i.get(in_b)]
        if not have:
            L += [f"### {title}", "", "*No database has both policies for this load yet.*", ""]
            continue
        any_data = True
        L += [f"### {title}", "",
              "| database | disk, deferred | disk, inline | change | time, deferred | time, inline "
              "| change |", "|---|---:|---:|---:|---:|---:|---:|"]
        for i in sorted(have, key=lambda x: -x["rows"]):
            db_pct = 100.0 * (i[in_b] - i[db_b]) / i[db_b]
            t_a, t_b = i.get(db_t), i.get(in_t)
            t_pct = (f"{100.0 * (t_b - t_a) / t_a:+.1f}%" if t_a and t_b else "—")
            L.append(f"| `{i['db']}` | {human(i[db_b])} | {human(i[in_b])} | {db_pct:+.1f}% "
                     f"| {secs(t_a)} | {secs(t_b)} | {t_pct} |")
        ta = sum(i[db_b] for i in have)
        tb = sum(i[in_b] for i in have)
        sa = sum(i.get(db_t) or 0 for i in have)
        sb = sum(i.get(in_t) or 0 for i in have)
        L.append(f"| **{len(have)} databases** | **{human(ta)}** | **{human(tb)}** "
                 f"| **{100.0 * (tb - ta) / ta:+.1f}%** | **{secs(sa)}** | **{secs(sb)}** "
                 f"| **{(f'{100.0 * (sb - sa) / sa:+.1f}%') if sa else '—'}** |")
        if len(have) < len(items):
            missing = sorted(i["db"] for i in items if i not in have)
            L.append(f"\n*{len(items) - len(have)} database(s) not yet measured under both "
                     "policies: " + ", ".join(f"`{d}`" for d in missing) + ".*")
        L.append("")
    if not any_data:
        return ""
    return "\n".join(L)


def secs(v):
    if not v:
        return "—"
    return f"{v:,.0f}s" if v < 3600 else f"{v / 3600:,.1f}h"


def cell(size, mysql):
    """Every Dolt figure is shown with what it is against MySQL. A size on its own invites the
    reader to compare columns by eye across three orders of magnitude, which is where the wrong
    conclusion comes from."""
    if not size:
        return "—"
    r = size / mysql
    return f"{human(size)}<br>**{r:.2f}×**" if r < 10 else f"{human(size)}<br>**{r:.0f}×**"


def environment_table():
    """The machine and the engine versions, from build/environment.json."""
    path = os.path.join(ROOT, "build", "environment.json")
    if not os.path.exists(path):
        return "*(run `make environment` to record the machine these numbers came from)*"
    e = json.load(open(path, encoding="utf-8"))
    h, d, g = e["host"], e["docker"], e["engines"]
    return "\n".join([
        "| | |", "|---|---|",
        f"| CPU | {h['cpu']} ({h['cpu_threads']} threads) |",
        f"| Memory | {h['memory']} |",
        f"| Disk | {h['disk_total']} {h['filesystem']} |",
        f"| Kernel | {h['kernel']} |",
        f"| Docker | {d['version']}, storage driver `{d['storage_driver']}` |",
        f"| MySQL | `{g['mysql_image']}` — {g['mysql_version']} |",
        f"| Dolt | `{g['dolt_image'].split('@')[0]}` — {g['dolt_version']} |",
        f"| Tuning | {g['tuning']} |",
        f"| MySQL flags | {', '.join('`' + f + '`' for f in g['mysql_flags'])} |",
    ])


def summary_table(items):
    """Every database, every test, disk and time. One table, so nothing is compared across
    populations by accident: a test with no result for a database shows an em dash."""
    L = ["| database | rows | 1. MySQL | 2. MySQL<br>row-wise | 3. Dolt<br>1 commit/db "
         "| 4. Dolt<br>1 INSERT/row | 5. Dolt<br>1 commit/row |",
         "|---|---:|---:|---:|---:|---:|---:|"]
    for i in sorted(items, key=lambda x: -(i_rows := x["rows"])):
        L.append(f"| `{i['db']}` | {i['rows']:,} "
                 f"| {human(i['mysql'])}<br>{secs(i['mysql_seconds'])} "
                 f"| {cell(i['mysql_rowwise_bytes'], i['mysql'])}<br>{secs(i['mysql_rowwise_seconds'])} "
                 f"| {cell(i['dolt'], i['mysql'])}<br>{secs(i['dolt_seconds'])} "
                 f"| {cell(i['rowinsert'], i['mysql'])}<br>{secs(i['rowinsert_seconds'])} "
                 f"| {cell(i['rowcommit'], i['mysql'])}<br>{secs(i['rowcommit_seconds'])} |")
    # totals over the databases where every test has a result, so the row is one population
    full = [i for i in items if all(i[k] for k in ("mysql", "mysql_rowwise_bytes", "dolt",
                                                   "rowinsert", "rowcommit"))]
    if full:
        b = {k: sum(i[k] for i in full) for k in ("mysql", "mysql_rowwise_bytes", "dolt",
                                                  "rowinsert", "rowcommit")}
        t = {k: sum(i[k] or 0 for i in full) for k in ("mysql_seconds", "mysql_rowwise_seconds",
                                                       "dolt_seconds", "rowinsert_seconds",
                                                       "rowcommit_seconds")}
        L.append(f"| **all {len(full)} with every test** | **{sum(i['rows'] for i in full):,}** "
                 f"| **{human(b['mysql'])}<br>{secs(t['mysql_seconds'])}** "
                 f"| **{b['mysql_rowwise_bytes'] / b['mysql']:.2f}×<br>{t['mysql_rowwise_seconds'] / t['mysql_seconds']:.0f}× time** "
                 f"| **{b['dolt'] / b['mysql']:.2f}×<br>{t['dolt_seconds'] / t['mysql_seconds']:.1f}× time** "
                 f"| **{b['rowinsert'] / b['mysql']:.2f}×<br>{t['rowinsert_seconds'] / t['mysql_seconds']:.0f}× time** "
                 f"| **{b['rowcommit'] / b['mysql']:.0f}×<br>{t['rowcommit_seconds'] / t['mysql_seconds']:.0f}× time** |")
    if len(full) < len(items):
        missing = sorted(i["db"] for i in items if i not in full)
        L.append(f"\n*Each cell is disk then time. {len(items) - len(full)} database(s) do not yet "
                 f"have every test and are excluded from the totals row: "
                 + ", ".join(f"`{d}`" for d in missing) + ".*")
    return "\n".join(L)


def report(items):
    my = sum(i["mysql"] for i in items)
    do = sum(i["dolt"] for i in items)
    ri = [i for i in items if i["rowinsert"]]
    rc = [i for i in items if i["rowcommit"]]
    smallest = min(items, key=lambda x: x["ratio"])
    largest = max(items, key=lambda x: x["ratio"])

    L = [GENERATED, "", "# Disk usage: MySQL 9.7.2 against Dolt 2.3.2", "",
         f"The same {len(items)} sample databases, {sum(i['rows'] for i in items):,} rows, loaded "
         "into both engines from the same `mysqldump` files and measured the same way: `du -sb` of "
         "the directory each engine keeps the database in.", "",
         "## The machine", "", environment_table(), "",
         "## The short answer: it depends on how you write the rows", "",
         "Dolt is a version-controlled database, so *how* the rows arrive decides what it stores. "
         "Three loads of identical data give three different answers, and they are not close:", "",
         "Both axes matter and they do not move together, so both are given for every load. MySQL "
         "is loaded from the same dumps into a fresh, empty server, and timed the same way.", "",
         "| load | databases | disk | ÷ MySQL | time | ÷ MySQL |", "|---|---:|---:|---:|---:|---:|"]

    mt = sum(i["mysql_seconds"] or 0 for i in items)
    L.append(f"| **MySQL**, extended `INSERT`s | {len(items)} | {human(my)} | — | {secs(mt)} | — |")
    dt = sum(i["dolt_seconds"] or 0 for i in items)
    L.append(f"| **Dolt**, one commit per database | {len(items)} | {human(do)} "
             f"| **{do / my:.2f}×** | {secs(dt)} | **{dt / mt:.1f}×** |" if mt else "")
    mrw = [i for i in items if i["mysql_rowwise_seconds"]]
    if mrw:
        b = sum(i["mysql_rowwise_bytes"] or 0 for i in mrw)
        t = sum(i["mysql_rowwise_seconds"] for i in mrw)
        base_b = sum(i["mysql"] for i in mrw)
        base_t = sum(i["mysql_seconds"] or 0 for i in mrw)
        L.append(f"| **MySQL**, one `INSERT` per row | {len(mrw)} | {human(b)} "
                 f"| {b / base_b:.2f}× | {secs(t)} | **{t / base_t:.0f}×** |")
    if ri:
        rmy = sum(i["mysql"] for i in ri)
        rmt = sum(i["mysql_seconds"] or 0 for i in ri)
        rt = sum(i["rowinsert_seconds"] or 0 for i in ri)
        L.append(f"| **Dolt**, one `INSERT` per row | {len(ri)} | {human(sum(i['rowinsert'] for i in ri))} "
                 f"| **{sum(i['rowinsert'] for i in ri) / rmy:.2f}×** | {secs(rt)} "
                 f"| **{rt / rmt:.0f}×** |")
    if rc:
        cmy = sum(i["mysql"] for i in rc)
        cmt = sum(i["mysql_seconds"] or 0 for i in rc)
        ct = sum(i["rowcommit_seconds"] or 0 for i in rc)
        L.append(f"| **Dolt**, one commit per row | {len(rc)} | {human(sum(i['rowcommit'] for i in rc))} "
                 f"| **{sum(i['rowcommit'] for i in rc) / cmy:.0f}×** | {secs(ct)} "
                 f"| **{ct / cmt:.0f}×** |")
    L += ["", "![What each load costs](docs/img/cost-by-mode.png)", "",
          "Read the two columns together. The standard Dolt load is a third of MySQL's disk for "
          "several times its load time — a trade, not a free win. Writing row by row is expensive in "
          "**both** engines, which is why MySQL is measured that way too: it separates what row-wise "
          "writing costs from what Dolt costs. And a commit per row is the one case where both "
          "axes go the wrong way at once.", ""]
    if rc:
        L += ["![Dolt ÷ MySQL for each load](docs/img/modes-vs-mysql.png)", "",
              "![Totalled over the databases measured in every mode](docs/img/totals-by-mode.png)", ""]

    # --- 1 ------------------------------------------------------------------------------------
    L += ["## 1. One commit per database", "",
          f"The standard load. **{human(do)} against MySQL's {human(my)} — {do / my:.2f}×** over "
          f"all {len(items)} databases, and the ratio is not uniform: it runs from "
          f"{smallest['ratio']:.2f}× (`{smallest['db']}`) to {largest['ratio']:.2f}× "
          f"(`{largest['db']}`), a spread of more than "
          f"{largest['ratio'] / smallest['ratio']:.0f} to one.", "",
          "![All databases](docs/img/totals.png)", "",
          "![Ratio per database](docs/img/ratio-by-database.png)", "",
          "The shape of the spread is legible. Small databases favour Dolt heavily because InnoDB "
          "allocates a tablespace per table whether or not anything is in it. Text-heavy data "
          "narrows the gap, because neither engine can compress prose. Dense numeric fact tables "
          "narrow it furthest — `oracle_sh` is close to InnoDB's best case.", ""]

    # --- 2 ------------------------------------------------------------------------------------
    if ri:
        deltas = sorted(abs(i["rowinsert"] - i["dolt"]) / i["dolt"] for i in ri)
        within = sum(1 for d in deltas if d <= 0.005)
        rmy = sum(i["mysql"] for i in ri)
        L += ["## 2. One `INSERT` per row, still one commit", "",
              "Replacing mysqldump's extended `INSERT`s with one statement per row changes the load "
              f"completely and the result **not at all**: {within} of the {len(ri)} databases land "
              f"within 0.5% of their one-shot size, and the widest differs by "
              f"{deltas[-1] * 100:.1f}%. Against MySQL the two loads are indistinguishable — "
              f"{sum(i['rowinsert'] for i in ri) / rmy:.2f}× against "
              f"{sum(i['dolt'] for i in ri) / rmy:.2f}× on the same databases.", "",
              "This is a real result rather than a non-event: statement batching is a load-time "
              "concern in Dolt exactly as it is in MySQL, and anyone reasoning about \"row by row\" "
              "storage costs is reasoning about the wrong granularity. It costs time — the largest "
              f"database here goes through {max(i['rows'] for i in ri):,} separate statements.", "",
              "| database | rows | MySQL | one commit | one INSERT per row | difference | vs MySQL |",
              "|---|---:|---:|---:|---:|---:|---:|"]
        for i in sorted(ri, key=lambda x: -x["rows"]):
            d = (i["rowinsert"] - i["dolt"]) / i["dolt"] * 100
            L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} | {human(i['dolt'])} "
                     f"| {human(i['rowinsert'])} | {d:+.1f}% "
                     f"| **{i['rowinsert'] / i['mysql']:.2f}×** |")
        L.append("")

    # --- 3 ------------------------------------------------------------------------------------
    if rc:
        cmy = sum(i["mysql"] for i in rc)
        cdo = sum(i["rowcommit"] for i in rc)
        cone = sum(i["dolt"] for i in rc)
        worst = max(rc, key=lambda x: x["rowcommit"] / x["mysql"])
        over = [i for i in rc if i["rowcommit"] > i["mysql"]]
        L += ["## 3. One commit per row", "",
              f"The same rows with a commit after each one take **{human(cdo)} where the one-commit "
              f"load takes {human(cone)}** — {cdo / cone:.0f}× more. Against MySQL the comparison "
              f"**inverts**: those databases are {cone / cmy:.2f}× MySQL loaded normally and "
              f"**{cdo / cmy:.0f}× MySQL** loaded a commit at a time, a swing of "
              f"{cdo / cone:.0f}× from nothing but how the rows were written.", "",
              f"{len(over)} of the {len(rc)} end up larger than MySQL. The extreme is "
              f"`{worst['db']}`: {worst['rows']:,} rows, {human(worst['mysql'])} in MySQL, "
              f"{human(worst['dolt'])} in one Dolt commit, {human(worst['rowcommit'])} in "
              f"{(worst['rowcommit_commits'] or 0):,} — **{worst['rowcommit'] / worst['mysql']:.0f}× "
              "MySQL for identical data**.", "",
              "![What history costs](docs/img/commit-granularity.png)", "",
              "| database | rows | MySQL | one commit | ÷MySQL | one commit per row | ÷MySQL | × one commit |",
              "|---|---:|---:|---:|---:|---:|---:|---:|"]
        for i in sorted(rc, key=lambda x: -x["rows"]):
            L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} | {human(i['dolt'])} "
                     f"| {i['dolt'] / i['mysql']:.2f}× | {human(i['rowcommit'])} "
                     f"| **{i['rowcommit'] / i['mysql']:.1f}×** "
                     f"| {i['rowcommit'] / i['dolt']:.0f}× |")
        L += [f"| **these {len(rc)}** | **{sum(i['rows'] for i in rc):,}** | **{human(cmy)}** "
              f"| **{human(cone)}** | **{cone / cmy:.2f}×** | **{human(cdo)}** "
              f"| **{cdo / cmy:.0f}×** | **{cdo / cone:.0f}×** |", "",
              "This is not overhead to be tuned away. Each commit is an addressable, diffable state "
              "of the whole database, and keeping a million of them costs what keeping a million of "
              "anything costs. The question the number answers is not \"is Dolt wasteful\" but "
              "**\"what does my commit rate cost me\"**, and it scales with commits, not with rows.", ""]

    # --- everything, together ------------------------------------------------------------------
    L += ["## Every database, every load", "",
          "`MySQL logical` is what `information_schema` reports (`data_length + index_length`) — "
          "always smaller than the directory, because it does not count free pages in the "
          "tablespace. `Dump` is the `mysqldump` SQL both engines were loaded from.", "",
          "| database | tables | rows | dump | MySQL logical | MySQL | one commit | one INSERT/row | one commit/row |",
          "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for i in sorted(items, key=lambda x: -x["mysql"]):
        L.append(f"| `{i['db']}` | {i['tables']} | {i['rows']:,} | {human(i['dump'])} "
                 f"| {human(i['logical'])} | {human(i['mysql'])} | {cell(i['dolt'], i['mysql'])} "
                 f"| {cell(i['rowinsert'], i['mysql'])} | {cell(i['rowcommit'], i['mysql'])} |")
    L.append(f"| **total** | {sum(i['tables'] for i in items)} | {sum(i['rows'] for i in items):,} "
             f"| {human(sum(i['dump'] for i in items))} | {human(sum(i['logical'] for i in items))} "
             f"| **{human(my)}** | **{human(do)}<br>{do / my:.2f}×** | | |")
    L.append("")

    missing_ri = [i["db"] for i in items if not i["rowinsert"]]
    missing_rc = [i["db"] for i in items if not i["rowcommit"]]
    if missing_ri or missing_rc:
        L += ["### Coverage", "",
              "The extra loads are expensive, and where a cell is empty the load has not been run "
              "rather than failed. `make experiment` runs them.", ""]
        if missing_ri:
            L.append(f"* **one `INSERT` per row** — not yet measured for {len(missing_ri)}: "
                     + ", ".join(f"`{d}`" for d in sorted(missing_ri)))
        if missing_rc:
            L.append(f"* **one commit per row** — not yet measured for {len(missing_rc)}: "
                     + ", ".join(f"`{d}`" for d in sorted(missing_rc)))
        L.append("")

    bad = [i for i in items if i["mismatch"]]
    idx_bad = [i for i in items if i["idx_diff"]]
    idx_my, idx_do = sum(i["idx_my"] for i in items), sum(i["idx_do"] for i in items)
    commits = sorted({i["commits"] for i in items if i["commits"]})
    L += ["## Is the comparison valid?", "",
          "Six things have to be true before a size ratio means anything. All six were checked on "
          "every database, not assumed. Three of them are checks on the data, below; the other "
          "three are properties of how the load is run, and each is here because it was once "
          "false: both engines are given the identical transformed dump (MySQL used to read "
          "mysqldump's original), every Dolt load ends with a commit and a clean `dolt_status` "
          "(the per-row-commit load used to end with `dolt gc` alone, leaving the index rebuild "
          "uncommitted), and every size is taken after `dolt gc` so a journal is never measured in "
          "place of a store.", "",
          "**The same rows.** `COUNT(*)` on both sides, per table, before any size was recorded; "
          "`information_schema.table_rows` is an InnoDB estimate and is not used. "
          + (f"**{len(bad)} database(s) disagree**: " + ", ".join(f"`{i['db']}`" for i in bad)
             if bad else "**Every table matches.**"), "",
          "**The same indexes.** Compared by definition — table, index name, column position, "
          "column, uniqueness — not by count. "
          + (f"**{len(idx_bad)} database(s) differ**: "
             + ", ".join(f"`{i['db']}`" for i in idx_bad) if idx_bad else
             f"**{idx_my} indexes in MySQL, {idx_do} in Dolt, identical in every database.**"), "",
          "Checked for every load, not only the one-shot one. The deferred policy takes the "
          "secondary indexes out of `CREATE TABLE` and rebuilds them with `ALTER TABLE` after the "
          "last row, so \"the same indexes at the end\" is exactly the thing it could get wrong:",
          ""] + index_parity_table(items) + ["",
          "**The history is stated, not assumed.** The one-commit load makes exactly one data commit "
          f"per database (`dolt_log` shows {', '.join(str(c) for c in commits)}, two of them Dolt's "
          "own `Initialize data repository` and `CREATE DATABASE`), and `dolt_status` is clean "
          "afterwards. That is the least history Dolt can hold, which is why section 3 exists: it "
          "measures the other end.", ""]

    served = sum(r.get("server_stats_bytes") or 0 for r in RAW.values())
    # The size adventureworks actually is, not a number typed in beside it. A hand-written figure
    # inside generated prose is the exact drift the claim checker exists to catch, and this one had
    # already drifted: 48.7 MB here against 49.0 MB in the journal, for the same database.
    aw_bytes = next((i["dolt"] for i in items if i["db"] == "adventureworks"), None)
    aw = human(aw_bytes) if aw_bytes else "the data"
    # 68.2 MB is an observation from this project's own console use, not something results.json
    # holds, so it stays as prose. The comparison against it must not be: "more than the 97.4 MB of
    # data they describe" is what the sentence said the moment the data was larger than the figure.
    aw_cmp = ("more than the" if aw_bytes and aw_bytes < 68.2 * 1000 * 1000
              else "against the")
    L += ["## What a running server adds, and why it is not in the figures", "",
          "Every size above was measured with **no server running**: the load is done by the `dolt` "
          "CLI and nothing serves the data afterwards. That is deliberate. A `dolt sql-server` "
          "writes a per-database statistics repository at `.dolt/stats`, `dolt gc` does not reclaim "
          "it, and mixing served and unserved directories is how an earlier version of this "
          "experiment produced a total that moved by 68 MB between runs for no visible reason.", "",
          f"Measured on a copy: starting a server and reading every table in every database wrote "
          f"**{human(served)}** in total, an even 22 KB per database.", "",
          "**That is a floor, not the cost.** During this project's own console use — four web "
          "clients browsing the data over a working session — `adventureworks`'s statistics reached "
          f"**68.2 MB, {aw_cmp} {aw} of data they describe**. A single pass over every table "
          "does not reproduce that, so the growth is driven by sustained querying in a way this "
          "experiment has not characterised. It is recorded because it is real disk that a real "
          "deployment will use, and because 22 KB would be a misleading thing to remember.", ""]

    policy = policy_section(items)
    if policy:
        L += [policy, ""]

    missing = [i for i in items if (i["views_my"] - i["views_do"]) or (i["rout_my"] - i["rout_do"])]
    if missing:
        L += ["## Schema objects Dolt would not take", "",
              "Views load once mysqldump's `ALGORITHM=` and `SQL SECURITY` clauses are removed. "
              "Stored functions do not load at all: Dolt rejects `CREATE FUNCTION`, and because one "
              "rejected statement aborts the rest of the routine section, a database loses all of "
              "its routines to the first function. None of this affects a row, which is why the "
              "counts above still match.", "",
              "| database | views MySQL → Dolt | routines MySQL → Dolt |", "|---|---|---|"]
        L += [f"| `{i['db']}` | {i['views_my']} → {i['views_do']} | {i['rout_my']} → {i['rout_do']} |"
              for i in missing]
        L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    results = load_results()
    global RAW
    RAW = results
    items = rows(results)
    if not items:
        sys.exit("no measurements in build/results.json; run scripts/measure.py first")

    text = report(items)
    readme = open(README, encoding="utf-8").read() if os.path.exists(README) else ""
    new_readme = readme
    if START in readme and END in readme:
        head, rest = readme.split(START, 1)
        _, tail = rest.split(END, 1)
        new_readme = f"{head}{START}\n{summary_table(items)}\n{END}{tail}"
    if ENV_START in new_readme and ENV_END in new_readme:
        head, rest = new_readme.split(ENV_START, 1)
        _, tail = rest.split(ENV_END, 1)
        new_readme = f"{head}{ENV_START}\n{environment_table()}\n{ENV_END}{tail}"

    if a.check:
        stale = []
        if not os.path.exists(REPORT) or open(REPORT, encoding="utf-8").read() != text:
            stale.append("REPORT.md")
        if new_readme != readme:
            stale.append("README.md")
        for s in stale:
            print(f"  x {s} is out of date; run `make report`")
        if stale:
            return 1
        print("  . REPORT.md and the README results are up to date")
        return 0

    open(REPORT, "w", encoding="utf-8").write(text)
    if new_readme != readme:
        open(README, "w", encoding="utf-8").write(new_readme)
    my, do = sum(i["mysql"] for i in items), sum(i["dolt"] for i in items)
    print(f"  . wrote REPORT.md: {len(items)} databases, MySQL {human(my)}, Dolt {human(do)}, "
          f"{do / my:.2f}x")
    return 0


if __name__ == "__main__":
    sys.exit(main())
