#!/usr/bin/env python3
"""Turn the measurements into the report, and splice the results into README.md.

  python3 scripts/report.py [--check]

Writes `REPORT.md` -- every database, both engines, the ratio -- and replaces the block between
`<!-- results:start -->` and `<!-- results:end -->` in `README.md` with the summary table. Both are
generated from `build/results.json`, so the numbers in the README are the numbers that were measured
and cannot be edited into something more flattering. `--check` exits non-zero if either is stale.
"""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, human, load_results  # noqa: E402

REPORT = os.path.join(ROOT, "REPORT.md")
README = os.path.join(ROOT, "README.md")
START, END = "<!-- results:start -->", "<!-- results:end -->"
GENERATED = ("<!-- Generated by scripts/report.py from build/results.json.\n"
             "     Do not edit by hand: `make report` overwrites it. -->")


def rows(results):
    out = []
    for db in sorted(results):
        r = results[db]
        modes = r.get("modes", {})
        one = modes.get("oneshot", {}) or {}
        my, do = r.get("mysql_disk_bytes"), one.get("disk_bytes")
        if not my or not do:
            continue
        out.append(dict(db=db, mysql=my, dolt=do, ratio=do / my,
                        rowinsert=(modes.get("rowinsert", {}) or {}).get("disk_bytes"),
                        rowcommit=(modes.get("rowcommit", {}) or {}).get("disk_bytes"),
                        rowcommit_commits=(modes.get("rowcommit", {}) or {}).get("commits"),
                        stats=one.get("stats_bytes") or 0,
                        idx_my=r.get("indexes_mysql") or 0, idx_do=one.get("indexes_dolt") or 0,
                        idx_diff=bool(one.get("indexes_only_mysql") or one.get("indexes_only_dolt")),
                        commits=one.get("commits"),
                        views_my=r.get("views_mysql") or 0, views_do=one.get("views_dolt") or 0,
                        rout_my=r.get("routines_mysql") or 0, rout_do=one.get("routines_dolt") or 0,
                        logical=r.get("mysql_logical_bytes") or 0,
                        dump=r.get("dump_bytes") or 0,
                        tables=r.get("tables") or 0, rows=r.get("rows_mysql") or 0,
                        mismatch=bool(one.get("row_mismatches")),
                        errors=one.get("statement_error_count", 0)))
    return out


def summary_table(items):
    L = ["| database | rows | MySQL | Dolt<br>one commit | Dolt<br>row INSERTs | "
         "Dolt<br>commit per row | Dolt ÷ MySQL |",
         "|---|---:|---:|---:|---:|---:|---:|"]
    for i in sorted(items, key=lambda x: -x["mysql"]):
        L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} | {human(i['dolt'])} "
                 f"| {human(i['rowinsert']) if i['rowinsert'] else '—'} "
                 f"| {human(i['rowcommit']) if i['rowcommit'] else '—'} "
                 f"| **{i['ratio']:.2f}×** |")
    my, do = sum(i["mysql"] for i in items), sum(i["dolt"] for i in items)
    ri = sum(i["rowinsert"] or 0 for i in items)
    L.append(f"| **all {len(items)}** | **{sum(i['rows'] for i in items):,}** | **{human(my)}** "
             f"| **{human(do)}** | **{human(ri) if ri else '—'}** | — | **{do / my:.2f}×** |")
    return "\n".join(L)


def report(items):
    my, do = sum(i["mysql"] for i in items), sum(i["dolt"] for i in items)
    smallest = min(items, key=lambda x: x["ratio"])
    largest = max(items, key=lambda x: x["ratio"])
    L = [GENERATED, "", "# Disk usage: MySQL 9.7.2 against Dolt 2.3.2", "",
         f"The same {len(items)} sample databases, {sum(i['rows'] for i in items):,} rows, loaded "
         "into both engines from the same `mysqldump` files and measured the same way: `du -sb` of "
         "the directory each engine keeps the database in.", "",
         f"**Dolt uses {human(do)} where MySQL uses {human(my)} — {do / my:.2f}× overall.** The "
         f"ratio is not uniform: it ranges from {smallest['ratio']:.2f}× (`{smallest['db']}`) to "
         f"{largest['ratio']:.2f}× (`{largest['db']}`).", "",
         "![All databases](docs/img/totals.png)", "",
         "![Ratio per database](docs/img/ratio-by-database.png)", "",
         "## Every database", "",
         "`MySQL on disk` and `Dolt on disk` are directory sizes. `MySQL logical` is what",
         "`information_schema` reports (`data_length + index_length`) — always smaller than the",
         "directory, because it does not count free pages in the tablespace. `Dump` is the",
         "`mysqldump` SQL both engines were loaded from, included as a size-independent reference",
         "point for how much data is actually there.", "",
         "![Disk used per database](docs/img/size-by-database.png)", "",
         "| database | tables | rows | dump | MySQL logical | MySQL on disk | Dolt on disk | Dolt ÷ MySQL |",
         "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for i in sorted(items, key=lambda x: -x["mysql"]):
        L.append(f"| `{i['db']}` | {i['tables']} | {i['rows']:,} | {human(i['dump'])} "
                 f"| {human(i['logical'])} | {human(i['mysql'])} | {human(i['dolt'])} "
                 f"| **{i['ratio']:.2f}×** |")
    L.append(f"| **total** | {sum(i['tables'] for i in items)} | {sum(i['rows'] for i in items):,} "
             f"| {human(sum(i['dump'] for i in items))} | {human(sum(i['logical'] for i in items))} "
             f"| **{human(my)}** | **{human(do)}** | **{do / my:.2f}×** |")

    # --- the three loads, side by side ---------------------------------------------------
    ri = [i for i in items if i["rowinsert"]]
    rc = [i for i in items if i["rowcommit"]]
    if ri:
        deltas = [abs(i["rowinsert"] - i["dolt"]) / i["dolt"] for i in ri]
        L += ["", "## Does it matter how the rows are written?", "",
              "Two more loads of the same data answer two different questions. The first replaces "
              "mysqldump's extended `INSERT`s with **one `INSERT` per row**, keeping a single commit. "
              "The second commits **after every row**.", "",
              "**Statement granularity changes nothing that is stored.** Across "
              f"{len(ri)} databases the row-by-row load lands within "
              f"{max(deltas) * 100:.1f}% of the one-shot load, and within "
              f"{sorted(deltas)[len(deltas) // 2] * 100:.1f}% at the median — noise from how chunks "
              "happen to pack, not a difference in what Dolt keeps. It costs a great deal of *time*: "
              "`dvdstore` takes "
              f"{max((i for i in ri if i['db'] == 'dvdstore'), key=lambda x: 0)['rows']:,} rows "
              "through 174,716 separate statements instead of a handful.", "",
              "| database | rows | one commit, extended INSERTs | one commit, one INSERT per row | difference |",
              "|---|---:|---:|---:|---:|"]
        for i in sorted(ri, key=lambda x: -x["rows"]):
            d = (i["rowinsert"] - i["dolt"]) / i["dolt"] * 100
            L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['dolt'])} | {human(i['rowinsert'])} "
                     f"| {d:+.1f}% |")
        L.append("")
    if rc:
        worst = max(rc, key=lambda x: x["rowcommit"] / x["dolt"])
        my_rc = sum(i["mysql"] for i in rc)
        do_rc = sum(i["rowcommit"] for i in rc)
        one_rc = sum(i["dolt"] for i in rc)
        L += ["**Commit granularity changes everything.** The same rows, committed one at a time, "
              f"take **{human(do_rc)} where the one-commit load takes {human(one_rc)}** — "
              f"{do_rc / one_rc:.0f}× more, and {do_rc / my_rc:.0f}× what MySQL uses for the same "
              f"data. The worst case here is `{worst['db']}`: {worst['rows']:,} rows, "
              f"{human(worst['dolt'])} in one commit, {human(worst['rowcommit'])} in "
              f"{(worst['rowcommit_commits'] or 0):,} commits.", "",
              "This is not overhead to be tuned away. It is what a version-controlled database is "
              "*for*: each commit is an addressable, diffable state of the whole database, and "
              "keeping a million of them costs what keeping a million of anything costs. The "
              "question it answers is not \"is Dolt wasteful\" but \"what does my commit rate cost "
              "me\", and the answer scales with commits, not rows.", "",
              "| database | rows | MySQL | Dolt, one commit | Dolt, commit per row | commits | × one commit |",
              "|---|---:|---:|---:|---:|---:|---:|"]
        for i in sorted(rc, key=lambda x: -x["rows"]):
            L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} | {human(i['dolt'])} "
                     f"| {human(i['rowcommit'])} | {(i['rowcommit_commits'] or 0):,} "
                     f"| **{i['rowcommit'] / i['dolt']:.0f}×** |")
        L += [f"| **these {len(rc)}** | **{sum(i['rows'] for i in rc):,}** | **{human(my_rc)}** "
              f"| **{human(one_rc)}** | **{human(do_rc)}** | | **{do_rc / one_rc:.0f}×** |", "",
              "Scope: the per-row-commit load ran on the smallest databases only. At the measured "
              f"rate it would need roughly {sum(i['rowcommit'] / i['rows'] for i in rc) / len(rc) * 9056697 / 1024**3:.0f} GB "
              "and several hours for all 9,056,697 rows, which buys no additional insight — the "
              "per-commit cost is already visible.", ""]

    bad = [i for i in items if i["mismatch"]]
    idx_bad = [i for i in items if i["idx_diff"]]
    idx_my, idx_do = sum(i["idx_my"] for i in items), sum(i["idx_do"] for i in items)
    stats = sum(i["stats"] for i in items)
    commits = sorted({i["commits"] for i in items if i["commits"]})
    L += ["", "## Is the comparison valid?", "",
          "Three things have to be true before a size ratio means anything. All three were checked "
          "on every database, not assumed.", "",
          "**The same rows.** Every table counted with `COUNT(*)` on both sides before any size was "
          "recorded; `information_schema.table_rows` is an InnoDB estimate and is not used. "
          + (f"**{len(bad)} database(s) disagree**: " + ", ".join(f"`{i['db']}`" for i in bad)
             if bad else "**Every table matches.**"), "",
          "**The same indexes.** Indexes are a large part of what a database costs on disk, so each "
          "one is compared by definition — table, index name, column position, column, uniqueness — "
          "and not by count. "
          + (f"**{len(idx_bad)} database(s) differ**: "
             + ", ".join(f"`{i['db']}`" for i in idx_bad) if idx_bad else
             f"**{idx_my} indexes in MySQL, {idx_do} in Dolt, identical in every database.**"), "",
          "**The least history Dolt can hold.** Dolt is a versioned database, so how much history it "
          "keeps changes what it stores. The load makes exactly **one data commit per database** — "
          f"`dolt_log` shows {', '.join(str(c) for c in commits)} commits, of which two are Dolt's "
          "own `Initialize data repository` and `CREATE DATABASE` — and `dolt_status` is clean "
          "afterwards, so nothing is sitting uncommitted where it would go unmeasured. Rows are not "
          "committed individually: the whole database arrives in one commit. **These numbers are "
          "therefore Dolt at its most favourable.** A branch, or a week of changes, would store "
          "more; this measures the floor.", ""]
    if stats:
        worst = max(items, key=lambda x: x["stats"])
        L += ["## What is deliberately not counted", "",
              f"A running `dolt sql-server` writes a per-database **statistics repository** at "
              f"`.dolt/stats` the first time it serves that database. Across these {len(items)} "
              f"databases it comes to **{human(stats)}**, and `dolt gc` does not reclaim it. The "
              f"largest is `{worst['db']}` at {human(worst['stats'])} — **more than the "
              f"{human(worst['dolt'])} of data it describes**.", "",
              "It is excluded from every figure above, for two reasons: it is the query planner's "
              "working notes rather than the database, and it does not exist until someone starts a "
              "server — so counting it would make the answer depend on whether anyone had happened "
              "to connect first. It is real disk all the same, which is why it is stated here.", "",
              "| database | data | server statistics |", "|---|---:|---:|"]
        L += [f"| `{i['db']}` | {human(i['dolt'])} | {human(i['stats'])} |"
              for i in sorted(items, key=lambda x: -x["stats"]) if i["stats"]]
        L.append("")

    missing = [i for i in items if (i["views_my"] - i["views_do"]) or (i["rout_my"] - i["rout_do"])]
    if missing:
        L += ["## Schema objects Dolt would not take", "",
              "Views load once mysqldump's `ALGORITHM=` and `SQL SECURITY` clauses are removed. "
              "Stored functions do not load at all: Dolt rejects `CREATE FUNCTION`, and because one "
              "rejected statement aborts the rest of the routine section, a database loses all of "
              "its routines to the first function. None of this affects a row, which is why the "
              "counts above still match.", "",
              "| database | views MySQL → Dolt | routines MySQL → Dolt |", "|---|---|---|"]
        L += [f"| `{i['db']}` | {i['views_my']} → {i['views_do']} | {i['rout_my']} → {i['rout_do']} |"
              for i in missing]
        L.append("")

    errs = [i for i in items if i["errors"]]
    if errs:
        L += ["Some statements in the dumps were rejected by Dolt. These are schema objects, not "
              "rows — the row counts above still match — but they are listed in `build/results.json` "
              "per database and summarised here:", "",
              "| database | statements Dolt rejected |", "|---|---:|"]
        L += [f"| `{i['db']}` | {i['errors']} |" for i in sorted(errs, key=lambda x: -x["errors"])]
        L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    results = load_results()
    items = rows(results)
    if not items:
        sys.exit("no measurements in build/results.json; run scripts/measure.py first")

    text = report(items)
    readme = open(README, encoding="utf-8").read() if os.path.exists(README) else ""
    new_readme = readme
    if START in readme and END in readme:
        head, rest = readme.split(START, 1)
        _, tail = rest.split(END, 1)
        new_readme = f"{head}{START}\n{summary_table(items)}\n{END}{tail}"

    if a.check:
        stale = []
        if not os.path.exists(REPORT) or open(REPORT, encoding="utf-8").read() != text:
            stale.append("REPORT.md")
        if new_readme != readme:
            stale.append("README.md")
        for s in stale:
            print(f"  x {s} is out of date; run `make report`")
        if stale:
            return 1
        print("  . REPORT.md and the README results are up to date")
        return 0

    open(REPORT, "w", encoding="utf-8").write(text)
    if new_readme != readme:
        open(README, "w", encoding="utf-8").write(new_readme)
    my, do = sum(i["mysql"] for i in items), sum(i["dolt"] for i in items)
    print(f"  . wrote REPORT.md: {len(items)} databases, MySQL {human(my)}, Dolt {human(do)}, "
          f"{do / my:.2f}x")
    return 0


if __name__ == "__main__":
    sys.exit(main())
