#!/usr/bin/env python3
"""Turn the measurements into the report, and splice the results into README.md.

  python3 scripts/report.py [--check]

Writes `REPORT.md` -- every database, both engines, the ratio -- and replaces the block between
`<!-- results:start -->` and `<!-- results:end -->` in `README.md` with the summary table. Both are
generated from `build/results.json`, so the numbers in the README are the numbers that were measured
and cannot be edited into something more flattering. `--check` exits non-zero if either is stale.
"""
import argparse, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, human, load_results  # noqa: E402

RAW = {}
REPORT = os.path.join(ROOT, "REPORT.md")
README = os.path.join(ROOT, "README.md")
START, END = "<!-- results:start -->", "<!-- results:end -->"
GENERATED = ("<!-- Generated by scripts/report.py from build/results.json.\n"
             "     Do not edit by hand: `make report` overwrites it. -->")


def rows(results):
    out = []
    for db in sorted(results):
        r = results[db]
        modes = r.get("modes", {})
        one = modes.get("oneshot", {}) or {}
        my, do = r.get("mysql_disk_bytes"), one.get("disk_bytes")
        if not my or not do:
            continue
        out.append(dict(db=db, mysql=my, dolt=do, ratio=do / my,
                        rowinsert=(modes.get("rowinsert", {}) or {}).get("disk_bytes"),
                        rowcommit=(modes.get("rowcommit", {}) or {}).get("disk_bytes"),
                        rowcommit_commits=(modes.get("rowcommit", {}) or {}).get("commits"),
                        stats=one.get("stats_bytes") or 0,
                        idx_my=r.get("indexes_mysql") or 0, idx_do=one.get("indexes_dolt") or 0,
                        idx_diff=bool(one.get("indexes_only_mysql") or one.get("indexes_only_dolt")),
                        commits=one.get("commits"),
                        views_my=r.get("views_mysql") or 0, views_do=one.get("views_dolt") or 0,
                        rout_my=r.get("routines_mysql") or 0, rout_do=one.get("routines_dolt") or 0,
                        logical=r.get("mysql_logical_bytes") or 0,
                        dump=r.get("dump_bytes") or 0,
                        tables=r.get("tables") or 0, rows=r.get("rows_mysql") or 0,
                        mismatch=bool(one.get("row_mismatches")),
                        errors=one.get("statement_error_count", 0)))
    return out


def cell(size, mysql):
    """Every Dolt figure is shown with what it is against MySQL. A size on its own invites the
    reader to compare columns by eye across three orders of magnitude, which is where the wrong
    conclusion comes from."""
    if not size:
        return "—"
    r = size / mysql
    return f"{human(size)}<br>**{r:.2f}×**" if r < 10 else f"{human(size)}<br>**{r:.0f}×**"


def summary_table(items):
    L = ["| database | rows | MySQL | Dolt<br>one commit | Dolt<br>one INSERT/row | "
         "Dolt<br>one commit/row |",
         "|---|---:|---:|---:|---:|---:|"]
    for i in sorted(items, key=lambda x: -x["mysql"]):
        L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} "
                 f"| {cell(i['dolt'], i['mysql'])} | {cell(i['rowinsert'], i['mysql'])} "
                 f"| {cell(i['rowcommit'], i['mysql'])} |")
    my, do = sum(i["mysql"] for i in items), sum(i["dolt"] for i in items)
    L.append(f"| **all {len(items)}** | **{sum(i['rows'] for i in items):,}** | **{human(my)}** "
             f"| **{human(do)}<br>{do / my:.2f}×** | | |")
    covered = [i for i in items if i["rowinsert"] and i["rowcommit"]]
    if covered:
        cmy = sum(i["mysql"] for i in covered)
        L.append(f"| *the {len(covered)} measured in every mode* | *{sum(i['rows'] for i in covered):,}* "
                 f"| *{human(cmy)}* "
                 f"| *{human(sum(i['dolt'] for i in covered))}<br>{sum(i['dolt'] for i in covered) / cmy:.2f}×* "
                 f"| *{human(sum(i['rowinsert'] for i in covered))}<br>{sum(i['rowinsert'] for i in covered) / cmy:.2f}×* "
                 f"| *{human(sum(i['rowcommit'] for i in covered))}<br>{sum(i['rowcommit'] for i in covered) / cmy:.0f}×* |")
    return "\n".join(L)


def report(items):
    my = sum(i["mysql"] for i in items)
    do = sum(i["dolt"] for i in items)
    ri = [i for i in items if i["rowinsert"]]
    rc = [i for i in items if i["rowcommit"]]
    smallest = min(items, key=lambda x: x["ratio"])
    largest = max(items, key=lambda x: x["ratio"])

    L = [GENERATED, "", "# Disk usage: MySQL 9.7.2 against Dolt 2.3.2", "",
         f"The same {len(items)} sample databases, {sum(i['rows'] for i in items):,} rows, loaded "
         "into both engines from the same `mysqldump` files and measured the same way: `du -sb` of "
         "the directory each engine keeps the database in.", "",
         "## The short answer: it depends on how you write the rows", "",
         "Dolt is a version-controlled database, so *how* the rows arrive decides what it stores. "
         "Three loads of identical data give three different answers, and they are not close:", "",
         "| load | what it does | against MySQL |", "|---|---|---:|"]

    L.append(f"| **one commit per database** | the way anyone would load a database | "
             f"**{do / my:.2f}×** across all {len(items)} |")
    if ri:
        rmy = sum(i["mysql"] for i in ri)
        L.append(f"| **one `INSERT` per row** | same commit, one statement per row instead of "
                 f"thousands of rows per statement | "
                 f"**{sum(i['rowinsert'] for i in ri) / rmy:.2f}×** across {len(ri)} |")
    if rc:
        cmy = sum(i["mysql"] for i in rc)
        L.append(f"| **one commit per row** | a commit for every row | "
                 f"**{sum(i['rowcommit'] for i in rc) / cmy:.0f}×** across {len(rc)} |")
    L += ["", "The first two are the same number. The third is not the same kind of number. Every "
          "section below gives each load the same treatment: what it costs, against MySQL, per "
          "database.", ""]
    if rc:
        L += ["![Dolt ÷ MySQL for each load](docs/img/modes-vs-mysql.png)", "",
              "![Totalled over the databases measured in every mode](docs/img/totals-by-mode.png)", ""]

    # --- 1 ------------------------------------------------------------------------------------
    L += ["## 1. One commit per database", "",
          f"The standard load. **{human(do)} against MySQL's {human(my)} — {do / my:.2f}×** over "
          f"all {len(items)} databases, and the ratio is not uniform: it runs from "
          f"{smallest['ratio']:.2f}× (`{smallest['db']}`) to {largest['ratio']:.2f}× "
          f"(`{largest['db']}`), a spread of more than "
          f"{largest['ratio'] / smallest['ratio']:.0f} to one.", "",
          "![All databases](docs/img/totals.png)", "",
          "![Ratio per database](docs/img/ratio-by-database.png)", "",
          "The shape of the spread is legible. Small databases favour Dolt heavily because InnoDB "
          "allocates a tablespace per table whether or not anything is in it. Text-heavy data "
          "narrows the gap, because neither engine can compress prose. Dense numeric fact tables "
          "narrow it furthest — `oracle_sh` is close to InnoDB's best case.", ""]

    # --- 2 ------------------------------------------------------------------------------------
    if ri:
        deltas = sorted(abs(i["rowinsert"] - i["dolt"]) / i["dolt"] for i in ri)
        within = sum(1 for d in deltas if d <= 0.005)
        rmy = sum(i["mysql"] for i in ri)
        L += ["## 2. One `INSERT` per row, still one commit", "",
              "Replacing mysqldump's extended `INSERT`s with one statement per row changes the load "
              f"completely and the result **not at all**: {within} of the {len(ri)} databases land "
              f"within 0.5% of their one-shot size, and the widest differs by "
              f"{deltas[-1] * 100:.1f}%. Against MySQL the two loads are indistinguishable — "
              f"{sum(i['rowinsert'] for i in ri) / rmy:.2f}× against "
              f"{sum(i['dolt'] for i in ri) / rmy:.2f}× on the same databases.", "",
              "This is a real result rather than a non-event: statement batching is a load-time "
              "concern in Dolt exactly as it is in MySQL, and anyone reasoning about \"row by row\" "
              "storage costs is reasoning about the wrong granularity. It costs time — the largest "
              f"database here goes through {max(i['rows'] for i in ri):,} separate statements.", "",
              "| database | rows | MySQL | one commit | one INSERT per row | difference | vs MySQL |",
              "|---|---:|---:|---:|---:|---:|---:|"]
        for i in sorted(ri, key=lambda x: -x["rows"]):
            d = (i["rowinsert"] - i["dolt"]) / i["dolt"] * 100
            L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} | {human(i['dolt'])} "
                     f"| {human(i['rowinsert'])} | {d:+.1f}% "
                     f"| **{i['rowinsert'] / i['mysql']:.2f}×** |")
        L.append("")

    # --- 3 ------------------------------------------------------------------------------------
    if rc:
        cmy = sum(i["mysql"] for i in rc)
        cdo = sum(i["rowcommit"] for i in rc)
        cone = sum(i["dolt"] for i in rc)
        worst = max(rc, key=lambda x: x["rowcommit"] / x["mysql"])
        over = [i for i in rc if i["rowcommit"] > i["mysql"]]
        L += ["## 3. One commit per row", "",
              f"The same rows with a commit after each one take **{human(cdo)} where the one-commit "
              f"load takes {human(cone)}** — {cdo / cone:.0f}× more. Against MySQL the comparison "
              f"**inverts**: those databases are {cone / cmy:.2f}× MySQL loaded normally and "
              f"**{cdo / cmy:.0f}× MySQL** loaded a commit at a time, a swing of "
              f"{cdo / cone:.0f}× from nothing but how the rows were written.", "",
              f"{len(over)} of the {len(rc)} end up larger than MySQL. The extreme is "
              f"`{worst['db']}`: {worst['rows']:,} rows, {human(worst['mysql'])} in MySQL, "
              f"{human(worst['dolt'])} in one Dolt commit, {human(worst['rowcommit'])} in "
              f"{(worst['rowcommit_commits'] or 0):,} — **{worst['rowcommit'] / worst['mysql']:.0f}× "
              "MySQL for identical data**.", "",
              "![What history costs](docs/img/commit-granularity.png)", "",
              "| database | rows | MySQL | one commit | ÷MySQL | one commit per row | ÷MySQL | × one commit |",
              "|---|---:|---:|---:|---:|---:|---:|---:|"]
        for i in sorted(rc, key=lambda x: -x["rows"]):
            L.append(f"| `{i['db']}` | {i['rows']:,} | {human(i['mysql'])} | {human(i['dolt'])} "
                     f"| {i['dolt'] / i['mysql']:.2f}× | {human(i['rowcommit'])} "
                     f"| **{i['rowcommit'] / i['mysql']:.1f}×** "
                     f"| {i['rowcommit'] / i['dolt']:.0f}× |")
        L += [f"| **these {len(rc)}** | **{sum(i['rows'] for i in rc):,}** | **{human(cmy)}** "
              f"| **{human(cone)}** | **{cone / cmy:.2f}×** | **{human(cdo)}** "
              f"| **{cdo / cmy:.0f}×** | **{cdo / cone:.0f}×** |", "",
              "This is not overhead to be tuned away. Each commit is an addressable, diffable state "
              "of the whole database, and keeping a million of them costs what keeping a million of "
              "anything costs. The question the number answers is not \"is Dolt wasteful\" but "
              "**\"what does my commit rate cost me\"**, and it scales with commits, not with rows.", ""]

    # --- everything, together ------------------------------------------------------------------
    L += ["## Every database, every load", "",
          "`MySQL logical` is what `information_schema` reports (`data_length + index_length`) — "
          "always smaller than the directory, because it does not count free pages in the "
          "tablespace. `Dump` is the `mysqldump` SQL both engines were loaded from.", "",
          "| database | tables | rows | dump | MySQL logical | MySQL | one commit | one INSERT/row | one commit/row |",
          "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for i in sorted(items, key=lambda x: -x["mysql"]):
        L.append(f"| `{i['db']}` | {i['tables']} | {i['rows']:,} | {human(i['dump'])} "
                 f"| {human(i['logical'])} | {human(i['mysql'])} | {cell(i['dolt'], i['mysql'])} "
                 f"| {cell(i['rowinsert'], i['mysql'])} | {cell(i['rowcommit'], i['mysql'])} |")
    L.append(f"| **total** | {sum(i['tables'] for i in items)} | {sum(i['rows'] for i in items):,} "
             f"| {human(sum(i['dump'] for i in items))} | {human(sum(i['logical'] for i in items))} "
             f"| **{human(my)}** | **{human(do)}<br>{do / my:.2f}×** | | |")
    L.append("")

    missing_ri = [i["db"] for i in items if not i["rowinsert"]]
    missing_rc = [i["db"] for i in items if not i["rowcommit"]]
    if missing_ri or missing_rc:
        L += ["### Coverage", "",
              "The extra loads are expensive, and where a cell is empty the load has not been run "
              "rather than failed. `make experiment` runs them.", ""]
        if missing_ri:
            L.append(f"* **one `INSERT` per row** — not yet measured for {len(missing_ri)}: "
                     + ", ".join(f"`{d}`" for d in sorted(missing_ri)))
        if missing_rc:
            L.append(f"* **one commit per row** — not yet measured for {len(missing_rc)}: "
                     + ", ".join(f"`{d}`" for d in sorted(missing_rc)))
        L.append("")

    bad = [i for i in items if i["mismatch"]]
    idx_bad = [i for i in items if i["idx_diff"]]
    idx_my, idx_do = sum(i["idx_my"] for i in items), sum(i["idx_do"] for i in items)
    commits = sorted({i["commits"] for i in items if i["commits"]})
    L += ["## Is the comparison valid?", "",
          "Three things have to be true before a size ratio means anything. All three were checked "
          "on every database, not assumed.", "",
          "**The same rows.** `COUNT(*)` on both sides, per table, before any size was recorded; "
          "`information_schema.table_rows` is an InnoDB estimate and is not used. "
          + (f"**{len(bad)} database(s) disagree**: " + ", ".join(f"`{i['db']}`" for i in bad)
             if bad else "**Every table matches.**"), "",
          "**The same indexes.** Compared by definition — table, index name, column position, "
          "column, uniqueness — not by count. "
          + (f"**{len(idx_bad)} database(s) differ**: "
             + ", ".join(f"`{i['db']}`" for i in idx_bad) if idx_bad else
             f"**{idx_my} indexes in MySQL, {idx_do} in Dolt, identical in every database.**"), "",
          "**The history is stated, not assumed.** The one-commit load makes exactly one data commit "
          f"per database (`dolt_log` shows {', '.join(str(c) for c in commits)}, two of them Dolt's "
          "own `Initialize data repository` and `CREATE DATABASE`), and `dolt_status` is clean "
          "afterwards. That is the least history Dolt can hold, which is why section 3 exists: it "
          "measures the other end.", ""]

    served = sum(r.get("server_stats_bytes") or 0 for r in RAW.values())
    L += ["## What a running server adds, and why it is not in the figures", "",
          "Every size above was measured with **no server running**: the load is done by the `dolt` "
          "CLI and nothing serves the data afterwards. That is deliberate. A `dolt sql-server` "
          "writes a per-database statistics repository at `.dolt/stats`, `dolt gc` does not reclaim "
          "it, and mixing served and unserved directories is how an earlier version of this "
          "experiment produced a total that moved by 68 MB between runs for no visible reason.", "",
          f"Measured on a copy: starting a server and reading every table in every database wrote "
          f"**{human(served)}** in total, an even 22 KB per database.", "",
          "**That is a floor, not the cost.** During this project's own console use — four web "
          "clients browsing the data over a working session — `adventureworks`'s statistics reached "
          "**68.2 MB, more than the 48.7 MB of data they describe**. A single pass over every table "
          "does not reproduce that, so the growth is driven by sustained querying in a way this "
          "experiment has not characterised. It is recorded because it is real disk that a real "
          "deployment will use, and because 22 KB would be a misleading thing to remember.", ""]

    missing = [i for i in items if (i["views_my"] - i["views_do"]) or (i["rout_my"] - i["rout_do"])]
    if missing:
        L += ["## Schema objects Dolt would not take", "",
              "Views load once mysqldump's `ALGORITHM=` and `SQL SECURITY` clauses are removed. "
              "Stored functions do not load at all: Dolt rejects `CREATE FUNCTION`, and because one "
              "rejected statement aborts the rest of the routine section, a database loses all of "
              "its routines to the first function. None of this affects a row, which is why the "
              "counts above still match.", "",
              "| database | views MySQL → Dolt | routines MySQL → Dolt |", "|---|---|---|"]
        L += [f"| `{i['db']}` | {i['views_my']} → {i['views_do']} | {i['rout_my']} → {i['rout_do']} |"
              for i in missing]
        L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    results = load_results()
    global RAW
    RAW = results
    items = rows(results)
    if not items:
        sys.exit("no measurements in build/results.json; run scripts/measure.py first")

    text = report(items)
    readme = open(README, encoding="utf-8").read() if os.path.exists(README) else ""
    new_readme = readme
    if START in readme and END in readme:
        head, rest = readme.split(START, 1)
        _, tail = rest.split(END, 1)
        new_readme = f"{head}{START}\n{summary_table(items)}\n{END}{tail}"

    if a.check:
        stale = []
        if not os.path.exists(REPORT) or open(REPORT, encoding="utf-8").read() != text:
            stale.append("REPORT.md")
        if new_readme != readme:
            stale.append("README.md")
        for s in stale:
            print(f"  x {s} is out of date; run `make report`")
        if stale:
            return 1
        print("  . REPORT.md and the README results are up to date")
        return 0

    open(REPORT, "w", encoding="utf-8").write(text)
    if new_readme != readme:
        open(README, "w", encoding="utf-8").write(new_readme)
    my, do = sum(i["mysql"] for i in items), sum(i["dolt"] for i in items)
    print(f"  . wrote REPORT.md: {len(items)} databases, MySQL {human(my)}, Dolt {human(do)}, "
          f"{do / my:.2f}x")
    return 0


if __name__ == "__main__":
    sys.exit(main())
